apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryvwj3044.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
          name: http-trips
          protocol: TCP
        imagePullPolicy: Always 
        env: 
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqluser
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlpassword
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlserver
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqldbname
        - name: "OPENAPI_DOCS_URI"
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  selector:
    app: trips
  ports:
    - port: 80
      targetPort: 80
      name: http-trips