apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryvwj3044.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
          name: http-userprof
          protocol: TCP
        imagePullPolicy: Always  
        env: 
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqluser
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlpassword
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlserver
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqldbname
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  selector:
    app: userprofile
  ports:
    - port: 80
      targetPort: 80
      name: http-userprof
